"""rename address

Revision ID: 897e90eb9c41
Revises: 2bdf329b289a
Create Date: 2025-03-11 14:44:54.772552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '897e90eb9c41'
down_revision = '2bdf329b289a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
